# Generated by Django 3.0.2 on 2020-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='test', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sub_category',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('Dress', 'Dresses'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes'), ('purse', 'Purse')], default='test2', max_length=6),
            preserve_default=False,
        ),
    ]
