# Generated by Django 3.0.2 on 2020-02-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200223_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='label',
            field=models.CharField(choices=[('Hot', 'Hot'), ('New', 'New'), ('Sale', 'Sale')], default='sale', max_length=4),
            preserve_default=False,
        ),
    ]
