# Generated by Django 3.0.3 on 2020-03-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item_images',
        ),
    ]
