# Generated by Django 3.0.2 on 2020-02-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200223_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Hot', 'hot'), ('New', 'new'), ('Sale', 'sale')], max_length=4),
        ),
    ]
