# Generated by Django 3.0.3 on 2020-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200303_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('sale', 'Sale')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_category',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('dress', 'Dresses'), ('jeans', 'Jeans'), ('shoes', 'Shoes'), ('purse', 'Purse')], max_length=6),
        ),
    ]
