# Generated by Django 3.0.3 on 2020-03-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200304_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('hot', 'hot'), ('new', 'new'), ('sale', 'sale')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_category',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('dress', 'Dresses'), ('jeans', 'Jeans'), ('shoes', 'Shoes'), ('purse', 'Purse')], default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='itemimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/product_images', verbose_name=''),
        ),
    ]
