# Generated by Django 3.0.2 on 2020-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200223_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='this is a test slug'),
            preserve_default=False,
        ),
    ]
