# Generated by Django 3.0.3 on 2020-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200315_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default='yyyy-mm-dd', null=True, verbose_name='Date of Birth'),
        ),
    ]
