# Generated by Django 3.0.3 on 2020-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200316_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default='1997-01-01', null=True, verbose_name='Date of Birth'),
        ),
    ]
