# Generated by Django 3.0.2 on 2020-02-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '__first__'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
